version: '2'

services:
  web:
    build: .
    ports:
      - "80:3000"

  forge:
    image: atmoz/sftp
    volumes:
      - /host/upload:/home/foo/upload
    ports:
      - "2222:22"
    command: foo:pass:1001
